name: vtuber
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - chzzkpy
    - langchain
    - langgraph
    - langchain-chroma
    - langchain-community
    - langchain-google-genai
    - langchain-groq
    - chromadb
    - edge-tts
    - websockets
    - pyaudio
    - sounddevice
    - soundfile
    - numpy
    - scipy
    - python-dotenv
    - ddgs